// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFoejmzvnw42ThL46pNHL2ETVk_dBY_WE',
    appId: '1:232098386541:web:a83bfe78bedb0e9e692564',
    messagingSenderId: '232098386541',
    projectId: 'ecommerceapp-cara',
    authDomain: 'ecommerceapp-cara.firebaseapp.com',
    storageBucket: 'ecommerceapp-cara.appspot.com',
    measurementId: 'G-N9LFJBMZYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjwld703-fdcLsFncElgKl2RbT9vReEMk',
    appId: '1:232098386541:android:fa3fccb58577b0dc692564',
    messagingSenderId: '232098386541',
    projectId: 'ecommerceapp-cara',
    storageBucket: 'ecommerceapp-cara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdsaRwF-BamnW0IdLlGPBSMPT9aZtAsog',
    appId: '1:232098386541:ios:fd260707683200f5692564',
    messagingSenderId: '232098386541',
    projectId: 'ecommerceapp-cara',
    storageBucket: 'ecommerceapp-cara.appspot.com',
    androidClientId: '232098386541-k087pln53adrt1u0lgqhm8igmkunu1et.apps.googleusercontent.com',
    iosClientId: '232098386541-r387uuijpakhe6716n72tvs4ejd6br0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFoejmzvnw42ThL46pNHL2ETVk_dBY_WE',
    appId: '1:232098386541:web:1a7821cd816a5aef692564',
    messagingSenderId: '232098386541',
    projectId: 'ecommerceapp-cara',
    authDomain: 'ecommerceapp-cara.firebaseapp.com',
    storageBucket: 'ecommerceapp-cara.appspot.com',
    measurementId: 'G-KG8FSQZF4N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdsaRwF-BamnW0IdLlGPBSMPT9aZtAsog',
    appId: '1:232098386541:ios:fd260707683200f5692564',
    messagingSenderId: '232098386541',
    projectId: 'ecommerceapp-cara',
    storageBucket: 'ecommerceapp-cara.appspot.com',
    androidClientId: '232098386541-k087pln53adrt1u0lgqhm8igmkunu1et.apps.googleusercontent.com',
    iosClientId: '232098386541-r387uuijpakhe6716n72tvs4ejd6br0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}